middleclass.lua: Makefile
	wget https://raw.githubusercontent.com/kikito/middleclass/master/middleclass.lua

stateful.lua: Makefile
	wget https://raw.githubusercontent.com/kikito/stateful.lua/master/stateful.lua
